// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCElevators.Data;

namespace SCElevators.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SCElevators.Data.Models.Elevator", b =>
                {
                    b.Property<int>("Number");

                    b.Property<string>("County");

                    b.Property<DateTimeOffset>("InsertedAt");

                    b.Property<DateTimeOffset>("LastSeen");

                    b.Property<string>("Location");

                    b.Property<string>("LocationAddress");

                    b.Property<string>("LocationCity");

                    b.Property<string>("LocationState");

                    b.Property<string>("LocationZip");

                    b.Property<string>("MachineType");

                    b.Property<string>("Manufacturer");

                    b.Property<DateTime?>("NextInspectionDue");

                    b.Property<string>("NextInspectionDueOther");

                    b.Property<string>("OwnerName");

                    b.Property<string>("Status");

                    b.Property<string>("UnitType");

                    b.HasKey("Number");

                    b.HasIndex("County");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Elevators");
                });
#pragma warning restore 612, 618
        }
    }
}
